#!/usr/bin/env python

"""
This script updates /etc/hosts on client machines so that the hosts found in
the sample web content resolve to experiment nodes acting as content servers.

The arguments to this script are a list of 'exphost=virthost' where 'exphost'
is the experiment host name, and 'virthost' is the content server it is
emulating.

"""

from os.path import exists
from os import rename
from sys import argv
from argparse import ArgumentParser

parser = ArgumentParser()
parser.add_argument('--keep', action='store_true', help='do not remove previously added hostnames')
parser.add_argument('hosts', nargs='+')
args = parser.parse_args()

hostmap = dict((p.split('=') for p in args.hosts))

# create a hosts file mapping the content servers to experiment hosts
if exists('/etc/hosts.orig') and not args.keep:
    suffix = '.orig'
else:
    suffix = ''

fin = open('/etc/hosts' + suffix, 'r')
fout = open('/tmp/hosts', 'w')

for e in fin:
    p = e.split()

    for h in p[1:]:
        if h in hostmap:
            print >>fout, e.rstrip(), hostmap[h]
            # print "hit :", e.rstrip(), hostmap[h]
            break
    else:
        print >>fout, e,
        # print "miss :", e,

fout.close()
fin.close()

if not exists('/etc/hosts.orig'):
    rename('/etc/hosts', '/etc/hosts.orig')
rename('/tmp/hosts', '/etc/hosts')
